apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpenv
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpenv
  template:
    metadata:
      labels:
        app: httpenv
    spec:
      containers:
      - name: httpenv
        image: bretfisher/httpenv:latest
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
